import streamlit as st
import components.Parameter_store as authenticate

def main():

    st.set_page_config(
        page_title="Education Home",
        page_icon="👋",
    )

    st.write("# Welcome to your education portal! 👋")

    st.markdown(
        """
        This portal is an AI platform for teachers to create course materials and 
        for students, to learn English words and sentences.
        ### What can teachers do?
        - Create questions from a sentence using a large language model 
        - Create an image based on the sentence using a text-to-image model
        - Save the sentence, the generated questions, and the generated image into an assignment bank
        - Browse assignments, generated questions, and generated images from the assignment bank
        ### What can students do?
        - Select and review an assignment from the assignment bank
        - Provide answers to the questions for the selected assignment 
        - See the grading scores of the answers generated by an NLP model
        - Check the suggested word improvements generated by an NLP model
        - Check the suggested sentence improvements generated by an NLP model
        """
    )

    hide_streamlit_style = """
        <style>
            #MainMenu {visibility: hidden;}
            footer{ visibility: hidden;}
        </style>
        """

    st.markdown(hide_streamlit_style, unsafe_allow_html=True)

if __name__ == '__main__':
    main()
